name: EVE Market Analysis

on:
  schedule:
    # Run daily at 3:00 AM UTC (offset from OSRS)
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      eve_budget:
        description: 'ISK budget (e.g., 1b, 500m)'
        required: true

jobs:
  eve-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
        
    - name: Run EVE Analysis
      env:
        BUDGET: ${{ github.event.inputs.eve_budget || '1b' }}
        GITHUB_ACTIONS: 'true'
      run: node src/eve.js
      
    - name: Prepare reports directory
      run: |
        mkdir -p docs/eve/archive
        REPORT_DATE=$(date +%Y-%m-%d)
        
        # Update main page with latest report
        cp email-report.html docs/eve/index.html
        
        # Archive dated report
        cp email-report.html docs/eve/archive/${REPORT_DATE}.html
        
        # Copy JSON data
        cp eve-results.json docs/eve/data.json
        cp eve-results.json docs/eve/archive/${REPORT_DATE}.json
        
    - name: Commit and push reports
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/eve/
        git commit -m "Update EVE market analysis - $(date +%Y-%m-%d)" || echo "No changes to commit"
        git push
