name: EVE Nightly Analysis

on:
  schedule:
    # Run daily at 3:00 AM UTC (offset from OSRS)
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      eve_budget:
        description: 'EVE ISK budget (e.g., 1b, 500m)'
        required: false

jobs:
  eve-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 300  # 5 hours max for EVE
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Run EVE Analysis
      env:
        BUDGET: ${{ github.event.inputs.eve_budget || '1b' }}
        GITHUB_ACTIONS: 'true'
      run: node eve.js
      
    - name: Upload EVE Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: eve-analysis-results-${{ github.run_number }}
        path: |
          eve-results.json
          eve-analysis.log
        retention-days: 30

  send-email-report:
    runs-on: ubuntu-latest
    needs: [eve-analysis]
    if: always()
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download EVE Results
      uses: actions/download-artifact@v4
      with:
        name: eve-analysis-results-${{ github.run_number }}
        path: ./results/eve/
      continue-on-error: true
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Generate Email Report
      run: node generate-email-report.js eve
      
    - name: Send Email Report
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "EVE Market Analysis Report - ${{ github.run_number }}"
        to: laserwolve@gmail.com
        from: PayForMyMembership Analysis <${{ secrets.EMAIL_USERNAME }}>
        html_body: file://email-report.html
        attachments: ./results/eve/eve-results.json
        priority: normal
