name: OSRS Market Analysis

on:
  schedule:
    # Run daily at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  osrs-analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
        
    - name: Run OSRS Analysis
      env:
        GITHUB_ACTIONS: 'true'
      run: node src/osrs.js
      
    - name: Prepare reports directory
      run: |
        mkdir -p docs/osrs/archive
        REPORT_DATE=$(date +%Y-%m-%d)
        
        # Update main page with latest report
        cp email-report.html docs/osrs/index.html
        
        # Archive dated report
        cp email-report.html docs/osrs/archive/${REPORT_DATE}.html
        cp osrs-results.json docs/osrs/archive/${REPORT_DATE}.json
        
    - name: Commit and push reports
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/osrs/
        git commit -m "Update OSRS market analysis - $(date +%Y-%m-%d)" || echo "No changes to commit"
        git push
