name: OSRS Market Analysis

on:
  schedule:
    # Run daily at 1:00 AM UTC
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      osrs_budget:
        description: 'OSRS budget (e.g., 10m, 500k, 2b)'
        required: false
        default: '50m'
      osrs_include_members:
        description: 'Include member items in OSRS analysis'
        required: false
        default: true
        type: boolean

jobs:
  osrs-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 180  # 3 hours max for OSRS
    if: vars.ENABLE_OSRS_ANALYSIS != 'false'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Run OSRS Analysis
      env:
        BUDGET: ${{ github.event.inputs.osrs_budget || '50m' }}
        INCLUDE_MEMBERS: ${{ github.event.inputs.osrs_include_members || 'true' }}
        GITHUB_ACTIONS: 'true'
      run: node osrs-github-runner.js
      
    - name: Upload OSRS Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: osrs-analysis-results-${{ github.run_number }}
        path: |
          osrs-results.json
          osrs-analysis.log
        retention-days: 30

    - name: Send OSRS Email Report
      uses: dawidd6/action-send-mail@v3
      if: success() && vars.ENABLE_EMAIL_REPORTS != 'false'
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "OSRS Market Analysis Report - ${{ github.run_number }}"
        to: laserwolve@gmail.com
        from: OSRS Analysis <${{ secrets.EMAIL_USERNAME }}>
        body: |
          OSRS Market Analysis Complete!
          
          Budget: ${{ env.BUDGET }}
          Include Members: ${{ env.INCLUDE_MEMBERS }}
          Run Number: ${{ github.run_number }}
          
          Check the artifacts for detailed results, or view the workflow logs for a summary.
          
          GitHub Actions run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        attachments: osrs-results.json
        priority: normal